"use client";

import { Typewriter } from 'react-simple-typewriter';
import { Button } from '@/components/ui/button';
import { SectionTitle } from '@/components/ui/section-title';
import { AiTipGenerator } from '@/components/ai/ai-tip-generator';
import Link from 'next/link';
import Image from 'next/image';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import {
  ArrowRight, Briefcase, BookOpen, Send, ShieldCheck,
    Network, Lock, ClipboardCheck, Target, MessagesSquare,
      ServerCog, ExternalLink
      } from 'lucide-react';
      import { projects } from '@/data/projects';
      import { ProjectCard } from '@/components/portfolio/project-card';

      const featuredProjects = projects.slice(0, 3);

      const expertiseItems = [
        { icon: ShieldCheck, title: 'Threat Intelligence', description: 'Proactive identification and analysis of cyber threats to preempt attacks.' },
          { icon: Network, title: 'Network Security', description: 'Designing and implementing secure network architectures and protocols.' },
            { icon: Lock, title: 'Ethical Hacking', description: 'Simulating attacks to identify vulnerabilities and strengthen defenses.' },
              { icon: ClipboardCheck, title: 'Security Audits', description: 'Identify vulnerabilities and ensure compliance.' },
                { icon: Target, title: 'Penetration Testing', description: 'Simulate real-world attacks to test defenses.' },
                  { icon: MessagesSquare, title: 'Security Consulting', description: 'Guidance for robust cybersecurity strategies.' },
                    { icon: ServerCog, title: 'MDR', description: '24/7 threat detection and response.' },
                    ];

                    export default function HomePage() {
                      return (
                          <div className="space-y-16">
                                <section className="text-center py-16 min-h-[70vh] flex flex-col justify-center items-center">
                                        <Image
                                                  src="https://placehold.co/150x150.png"
                                                            alt="Umer Farooq"
                                                                      width={150}
                                                                                height={150}
                                                                                          className="rounded-full mx-auto mb-8 border-4 border-primary animate-slide-in-down opacity-0"
                                                                                                    data-ai-hint="professional portrait"
                                                                                                            />
                                                                                                                    <h1 className="text-4xl md:text-5xl lg:text-6xl font-cyberName mb-6 text-primary animate-neon-glow-primary">
                                                                                                                              <Typewriter
                                                                                                                                          words={["Hi, I'm Umer Farooq | Cybersecurity Specialist 🔒"]}
                                                                                                                                                      loop={1}
                                                                                                                                                                  cursor
                                                                                                                                                                              cursorStyle='_'
                                                                                                                                                                                          typeSpeed={70}
                                                                                                                                                                                                      deleteSpeed={50}
                                                                                                                                                                                                                  delaySpeed={1000}
                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                    </h1>
                                                                                                                                                                                                                                            <p className="max-w-2xl mx-auto text-lg text-muted-foreground mb-8 animate-slide-in-down opacity-0">
                                                                                                                                                                                                                                                      Safeguarding digital landscapes with advanced threat analysis and expert insights from Faisalabad, Pakistan.
                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                      <div className="space-x-4 animate-slide-in-down opacity-0">
                                                                                                                                                                                                                                                                                <Button asChild size="lg">
                                                                                                                                                                                                                                                                                            <Link href="/portfolio">
                                                                                                                                                                                                                                                                                                          View My Work <Briefcase className="ml-2 h-5 w-5" />
                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                </Button>
                                                                                                                                                                                                                                                                                                                                          <Button asChild size="lg" variant="outline">
                                                                                                                                                                                                                                                                                                                                                      <Link href="/contact">
                                                                                                                                                                                                                                                                                                                                                                    Get In Touch <Send className="ml-2 h-5 w-5" />
                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                          </Button>
                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                        </section>

                                                                                                                                                                                                                                                                                                                                                                                                              <section id="expertise" className="py-12">
                                                                                                                                                                                                                                                                                                                                                                                                                      <SectionTitle className="text-center animate-glitch">My Expertise</SectionTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="grid md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                        {expertiseItems.map((item, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Card
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={item.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="flex flex-col items-center animate-slide-in-down opacity-0"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ animationDelay: `${0.5 + index * 0.1}s` }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <CardHeader className="pb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <item.icon className="h-12 w-12 text-primary mx-auto mb-3" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <CardTitle>{item.title}</CardTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </CardHeader>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-muted-foreground">{item.description}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <section id="featured-projects" className="py-12">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <SectionTitle className="text-center animate-glitch">Featured Projects</SectionTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {featuredProjects.map((project, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div key={project.id} className="animate-slide-in-down opacity-0" style={{ animationDelay: `${0.5 + index * 0.1}s` }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <ProjectCard project={project} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="text-center mt-12 animate-slide-in-down opacity-0" style={{ animationDelay: `${0.5 + featuredProjects.length * 0.1}s` }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Button asChild size="lg" variant="outline">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link href="/portfolio">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          View All Projects <ExternalLink className="ml-2 h-5 w-5" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <section id="ai-tip" className="py-12 animate-slide-in-down opacity-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <AiTipGenerator />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <section id="cta-blog" className="py-12 text-center bg-card rounded-lg p-8 animate-slide-in-down opacity-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <SectionTitle className="animate-glitch">Stay Informed</SectionTitle>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="max-w-xl mx-auto text-muted-foreground mb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Explore my latest articles and insights on cybersecurity trends, best practices, and threat landscapes.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Button asChild size="lg" className="bg-accent hover:bg-accent/90 text-accent-foreground">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link href="/blog">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Read The Blog <BookOpen className="ml-2 h-5 w-5" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      